### ISSUE TITLE
FragmentManager example

### ISSUE THREAD

**Issue by ghchinoy** [inazaruk/map-fragment#2]
now that LocalActivityManager is deprecated in API 13, can someone update this example using FragmentManager?

**Comment by inazaruk** [comment]
Nope. Basically LocalActivityManager is used to host Activity (MapActivity). This can't be done with FragmentManager alone. 

LocalActivityManager is deprecated in favor of Fragments. But there is no MapFragment, hence we need to embed MapActivity as fragment. And this cannot be done without LocalActivityManager.

**Comment by ghchinoy** [comment]
Ok, subsequent looking around pointed here: http://code.google.com/p/android/issues/detail?id=15347
I understand your answer now.
